import React from 'react';import {View} from 'react-native';import {Stack,StyledPressable} from 'fluent-styles';import {useSafeAreaInsets} from 'react-native-safe-area-context';import {useRouter} from 'expo-router';import * as Haptics from 'expo-haptics';import {useColors} from '../constants';import {Text} from './text';import {PremiumIcon,PremiumIconName} from './PremiumIcon';
const META:Record<string,[PremiumIconName,string]>={index:['home','Home'],tasks:['tasks','Tasks'],exams:['exam','Exams'],settings:['settings','Settings']};
// Rendered height of the pill itself (paddingVertical 7*2 + icon/label column
// ~48), NOT including the safe-area gap below it. The bar floats as an
// absolute overlay across the full screen (not in a reserved strip), so any
// screen-level FAB on a tab root must clear `insets.bottom + this` or its
// lower portion sits behind the bar's touchable area and swallows taps.
export const FLOATING_TAB_BAR_HEIGHT=64;
export function FloatingTabBar({state,navigation}:any){const C=useColors(),ins=useSafeAreaInsets(),router=useRouter();const routes=state.routes.filter((x:any)=>META[x.name]);return <View pointerEvents="box-none" style={{position:'absolute',left:16,right:16,bottom:Math.max(ins.bottom,10)}}><Stack flexDirection="row" alignItems="center" backgroundColor={C.bgCard} borderRadius={28} paddingHorizontal={8} paddingVertical={7} borderWidth={1} borderColor={C.border} style={{shadowColor:'#111827',shadowOpacity:.13,shadowRadius:22,shadowOffset:{width:0,height:9},elevation:12}}>{routes.map((route:any,i:number)=>{const originalIndex=state.routes.findIndex((x:any)=>x.key===route.key),focused=state.index===originalIndex;const [icon,label]=META[route.name];return <React.Fragment key={route.key}>{i===2?<StyledPressable width={58} height={58} marginHorizontal={4} marginTop={-26} borderRadius={29} backgroundColor={C.primary} borderWidth={4} borderColor={C.bgCard} alignItems="center" justifyContent="center" style={{shadowColor:C.primary,shadowOpacity:.3,shadowRadius:12,shadowOffset:{width:0,height:5}}} onPress={()=>{Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);router.push('/quick-add' as any)}}><PremiumIcon name="plus" size={25} color={C.white} strokeWidth={2.2}/></StyledPressable>:null}<StyledPressable flex={1} alignItems="center" justifyContent="center" paddingVertical={6} gap={3} onPress={()=>{Haptics.selectionAsync();navigation.navigate(route.name)}}><PremiumIcon name={icon} size={20} color={focused?C.primary:C.textMuted} strokeWidth={focused?2.2:1.8}/><Text fontSize={10} fontWeight={focused?'700':'600'} color={focused?C.primary:C.textMuted}>{label}</Text></StyledPressable></React.Fragment>})}</Stack></View>}
